### ISSUE TITLE
Authentication inconsistently fails against certain servers

### ISSUE THREAD

**Issue by vordenken** [maxgoedjen/secretive#82]
I wanted to try this software so I generated a new keypair with it and copied the public key to my testserver. When trying to connect to it, a password prompt appears even after the publickey got acceptet (As seen in the log). This does not happen if I use the same setup with my ssh key in my .ssh folder.
```
debug1: Authentications that can continue: publickey,password
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA SHA256:RANDOMSTRING agent
debug1: Server accepts key: ecdsa-sha2-nistp256 ECDSA SHA256:RANDOMSTRING agent
debug1: Authentications that can continue: publickey,password
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA SHA256:RANDOMSTRING agent
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /Users/admin/.ssh/id_rsa
debug1: Trying private key: /Users/admin/.ssh/id_dsa
debug1: Trying private key: /Users/admin/.ssh/id_ecdsa
debug1: Trying private key: /Users/admin/.ssh/id_ed25519
debug1: Trying private key: /Users/admin/.ssh/id_xmss
debug1: Next authentication method: password
user@192.168.1.10's password:
```
If theres  some kind of log I can provide let me know.

**Comment by maxgoedjen** [comment]
Hey @vordenken – can you paste the console log from `ssh -Tv git@github.com`?

**Comment by vordenken** [comment]
I don't know why, but Github is (the only) working. 
Gitlab or Codeberg dont work. The log in my first post is from ```ssh -Tv git@codeberg.org```

Could it be a problem that I'm offering to many keys while trying to connect? 
Normally I use a config file for ssh in which I declare one host one key.

**Comment by blowery** [comment]
I've been seeing this behavior too. Sometimes it'll connect, sometimes it will not. It may be related to how fast I'm able to register my fingerprint with the scanner?

**Comment by blowery** [comment]
Works fine with github, but not with my own machine running `OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g`. It seems to work if I _very quickly_ scan my fingerprint. If I delay at all, it fails and moves on.

**Comment by vordenken** [comment]
So I tried your theorie with a fast scan first- gitlab, github & codeberg worked. But after that the slow scan also worked on all three... 
I don't know why its now working at all. 7 hours ago it didn't.

**Comment by maxgoedjen** [comment]
Curious. My suspicion is it's something to do with the ssh configuration on the other end of the connection. I'll experiment with Codeberg and see what it does.

**Comment by maxgoedjen** [comment]
Here's the output I'm getting from codeberg, for posterity

```
 ~  ssh -Tv git@codeberg.org                                                                               255 
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to codeberg.org port 22.
debug1: Connection established.
debug1: identity file /Users/max/.ssh/id_rsa type 0
debug1: identity file /Users/max/.ssh/id_rsa-cert type -1
debug1: identity file /Users/max/.ssh/id_dsa type -1
debug1: identity file /Users/max/.ssh/id_dsa-cert type -1
debug1: identity file /Users/max/.ssh/id_ecdsa type -1
debug1: identity file /Users/max/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/max/.ssh/id_ed25519 type -1
debug1: identity file /Users/max/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/max/.ssh/id_xmss type -1
debug1: identity file /Users/max/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debian-10+deb10u2
debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to codeberg.org:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:T9FYDEHELhVkulEKKwge5aVhVTbqCW0MIRwAfpARs/E
The authenticity of host 'codeberg.org (159.69.0.178)' can't be established.
ECDSA key fingerprint is SHA256:T9FYDEHELhVkulEKKwge5aVhVTbqCW0MIRwAfpARs/E.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'codeberg.org,159.69.0.178' (ECDSA) to the list of known hosts.
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: ecdsa-sha2-nistp384 ECDSA SHA256:o2uNXB/DH9dYCVoKYsoGPLZ99iZg+pnrCLoQtRthnUg agent
debug1: Will attempt key: ecdsa-sha2-nistp384 ECDSA SHA256:O8+8vqSIBoILmuHW25rFpT/Xz/wO0v7OKTAXzbJs5vE agent
debug1: Will attempt key: /Users/max/.ssh/id_rsa RSA SHA256:ql1ns5Y9M8hMKeIGoFjsZasu0UMW9pibObA7cgc0fnM
debug1: Will attempt key: /Users/max/.ssh/id_dsa 
debug1: Will attempt key: /Users/max/.ssh/id_ecdsa 
debug1: Will attempt key: /Users/max/.ssh/id_ed25519 
debug1: Will attempt key: /Users/max/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: ecdsa-sha2-nistp384 ECDSA SHA256:o2uNXB/DH9dYCVoKYsoGPLZ99iZg+pnrCLoQtRthnUg agent
debug1: Server accepts key: ecdsa-sha2-nistp384 ECDSA SHA256:o2uNXB/DH9dYCVoKYsoGPLZ99iZg+pnrCLoQtRthnUg agent
```
[HOLD FOR AUTHENTICATION STEP]
```
debug1: Authentications that can continue: publickey,password
debug1: Offering public key: ecdsa-sha2-nistp384 ECDSA SHA256:O8+8vqSIBoILmuHW25rFpT/Xz/wO0v7OKTAXzbJs5vE agent
debug1: Authentications that can continue: publickey,password
debug1: Offering public key: /Users/max/.ssh/id_rsa RSA SHA256:ql1ns5Y9M8hMKeIGoFjsZasu0UMW9pibObA7cgc0fnM
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /Users/max/.ssh/id_dsa
debug1: Trying private key: /Users/max/.ssh/id_ecdsa
debug1: Trying private key: /Users/max/.ssh/id_ed25519
debug1: Trying private key: /Users/max/.ssh/id_xmss
debug1: Next authentication method: password
```

**Comment by maxgoedjen** [comment]
It does _not_ (at least in this example) appear to be timing related.

**Comment by maxgoedjen** [comment]
Comparing to GitHub

```
 ~  ssh -Tv git@github.com                                                                                   1 
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to github.com port 22.
debug1: Connection established.
debug1: identity file /Users/max/.ssh/id_rsa type 0
debug1: identity file /Users/max/.ssh/id_rsa-cert type -1
debug1: identity file /Users/max/.ssh/id_dsa type -1
debug1: identity file /Users/max/.ssh/id_dsa-cert type -1
debug1: identity file /Users/max/.ssh/id_ecdsa type -1
debug1: identity file /Users/max/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/max/.ssh/id_ed25519 type -1
debug1: identity file /Users/max/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/max/.ssh/id_xmss type -1
debug1: identity file /Users/max/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version babeld-72deb3a2
debug1: no match: babeld-72deb3a2
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /Users/max/.ssh/known_hosts:2
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: ecdsa-sha2-nistp384 ECDSA SHA256:o2uNXB/DH9dYCVoKYsoGPLZ99iZg+pnrCLoQtRthnUg agent
debug1: Will attempt key: ecdsa-sha2-nistp384 ECDSA SHA256:O8+8vqSIBoILmuHW25rFpT/Xz/wO0v7OKTAXzbJs5vE agent
debug1: Will attempt key: /Users/max/.ssh/id_rsa RSA SHA256:ql1ns5Y9M8hMKeIGoFjsZasu0UMW9pibObA7cgc0fnM
debug1: Will attempt key: /Users/max/.ssh/id_dsa 
debug1: Will attempt key: /Users/max/.ssh/id_ecdsa 
debug1: Will attempt key: /Users/max/.ssh/id_ed25519 
debug1: Will attempt key: /Users/max/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: ecdsa-sha2-nistp384 ECDSA SHA256:o2uNXB/DH9dYCVoKYsoGPLZ99iZg+pnrCLoQtRthnUg agent
debug1: Server accepts key: ecdsa-sha2-nistp384 ECDSA SHA256:o2uNXB/DH9dYCVoKYsoGPLZ99iZg+pnrCLoQtRthnUg agent
debug1: Authentication succeeded (publickey).
Authenticated to github.com ([192.30.255.113]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
Hi maxgoedjen! You've successfully authenticated, but GitHub does not provide shell access.
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2268, received 2100 bytes, in 0.2 seconds
Bytes per second: sent 12190.8, received 11287.8
debug1: Exit status 1
```

Both GitHub (successfully) and codeberg (failure) have same console output from SecretAgent, as near as I can tell.

**Comment by maxgoedjen** [comment]
<img width="1878" alt="Screen Shot 2020-03-31 at 11 24 22 PM" src="https://user-images.githubusercontent.com/342665/78105753-c2e87100-73a6-11ea-86a6-13be2512c553.png">
In diff form – basically from what I'm seeing, it accepts the publicly, but the actual signature fails/is rejected silently, for some reason.

**Comment by maxgoedjen** [comment]
For reference, this app was basically developed against GitHub as a reference/testing API – very possible there are compatibility issues (like this) that I'm not aware of. Thank you for bringing it to my attention @vordenken

**Comment by maxgoedjen** [comment]
Seeing similar behavior now to what you were describing – it sometimes working and sometimes not. Comparison between the two doesn't seem to reveal anything very interesting...

**Comment by vordenken** [comment]
I thought its maybe some kind of configuration at codeberg or gitlab. Because of that I used ubuntu and debian vms for testing as well & saw the same behaviour. Its really weird because I can not see a pattern. Sometimes it works and sometimes it don't..

**Comment by maxgoedjen** [comment]
Yeah the nondeterministic aspect is extra weird. Both codeberg and gitlab are using Ubuntu SSH, it’s plausible some servers are configured differently and you’re getting load balanced to good/bad ones randomly, but the configuration data -vvv outputs doesn’t really support this. My guess is there’s some cryptographic operation that’s giving me bad output sometimes (that githubs ssh either doesn’t enforce or notice).

**Comment by jrmguimberteau** [comment]
I've been seeing this behavior too (with gitlab).

`ssh -Tv git@gitlab.com`

`debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/jeremy/.ssh/id_rsa
debug1: Trying private key: /Users/jeremy/.ssh/id_dsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ecdsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ed25519
debug1: Trying private key: /Users/jeremy/.ssh/id_xmss
debug1: No more authentication methods to try.
git@gitlab.com: Permission denied (publickey).`

**Comment by jrmguimberteau** [comment]
I've been seeing this behavior too (with gitlab).

`ssh -Tv git@gitlab.com`

> debug1: Authentications that can continue: publickey
> debug1: Trying private key: /Users/jeremy/.ssh/id_rsa
> debug1: Trying private key: /Users/jeremy/.ssh/id_dsa
> debug1: Trying private key: /Users/jeremy/.ssh/id_ecdsa
> debug1: Trying private key: /Users/jeremy/.ssh/id_ed25519
> debug1: Trying private key: /Users/jeremy/.ssh/id_xmss
> debug1: No more authentication methods to try.
> git@gitlab.com: Permission denied (publickey).

**Comment by jrmguimberteau** [comment]
I've been seeing this behavior too (with gitlab).

`ssh -Tv git@gitlab.com`
```
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/jeremy/.ssh/id_rsa
debug1: Trying private key: /Users/jeremy/.ssh/id_dsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ecdsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ed25519
debug1: Trying private key: /Users/jeremy/.ssh/id_xmss
debug1: No more authentication methods to try.
git@gitlab.com: Permission denied (publickey).
```

**Comment by jrmguimberteau** [comment]
I've been seeing this behavior too (with gitlab). But with GitHub, I didn't have any problems.

`jeremy@macbookpro ~ % ssh -Tv git@gitlab.com`
```
...
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/jeremy/.ssh/id_rsa
debug1: Trying private key: /Users/jeremy/.ssh/id_dsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ecdsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ed25519
debug1: Trying private key: /Users/jeremy/.ssh/id_xmss
debug1: No more authentication methods to try.
git@gitlab.com: Permission denied (publickey).
```

**Comment by maxgoedjen** [comment]
Running it through my signature tests passes for a failed request response/reply.

```
        let request = OpenSSHReader(data: Data(base64Encoded: "AAABhA0AAACIAAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBEqCbkJbOHy5S1wVCaJoKPmpS0egM4frMqllgnlRRQ/Uvnn6EVS8oV03cPA2Bz0EdESyRKA/sbmn0aBtgjIwGELxu45UXEW1TEz6TxyS0u3vuIqR3Wo1CrQWRDnkrG/pBQAAAO8AAAAgwZGm0LuItDV7jEsutaSnSFWlJTtxx7Q3gDiSRGh4/p4yAAAAA2dpdAAAAA5zc2gtY29ubmVjdGlvbgAAAAlwdWJsaWNrZXkBAAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAACIAAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBEqCbkJbOHy5S1wVCaJoKPmpS0egM4frMqllgnlRRQ/Uvnn6EVS8oV03cPA2Bz0EdESyRKA/sbmn0aBtgjIwGELxu45UXEW1TEz6TxyS0u3vuIqR3Wo1CrQWRDnkrG/pBQAAAAA=")![5...])
        _ = request.readNextChunk()
        let dataToSign = request.readNextChunk()
        let pk = Data(base64Encoded: "BEqCbkJbOHy5S1wVCaJoKPmpS0egM4frMqllgnlRRQ/Uvnn6EVS8oV03cPA2Bz0EdESyRKA/sbmn0aBtgjIwGELxu45UXEW1TEz6TxyS0u3vuIqR3Wo1CrQWRDnkrG/pBQ==")!
        let response = Data(base64Encoded: "AAAAiA4AAACDAAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAABoAAAAMKeNmZ0j1/x0cetuxyQyc+BNJcAUHeVp/tZc+3TBOU4lfgJUhITnSdMJdcPkQc2YHAAAADB8NgEISEsI5LvNpdnmqnlWtHu6lTyj2ikXEP4Wp9y1PEiLqT13onmQODLH8C762hU=")!
        let outer = OpenSSHReader(data: response[5...])
        let payload = outer.readNextChunk()
        let inner = OpenSSHReader(data: payload)
        _ = inner.readNextChunk()
        let signedData = inner.readNextChunk()
        let rsData = OpenSSHReader(data: signedData)
        let r = rsData.readNextChunk()
        let s = rsData.readNextChunk()
        var rs = r
        rs.append(s)
        let signature = try! P384.Signing.ECDSASignature(rawRepresentation: rs)
        let valid = try! P384.Signing.PublicKey(x963Representation: pk).isValidSignature(signature, for: dataToSign)
        XCTAssertTrue(valid)
```
🤔

**Comment by maxgoedjen** [comment]
@vordenken if you have test servers running that you can reproduce the failure on, would it be possible for you to run sshd in debug mode in those VMs? I'd be highly curious if there was any extra loggin that'd be revealing on the other end.

**Comment by maxgoedjen** [comment]
Alright, maybe getting somewhere. sshd with VERBOSE logs on shows this for failed attempts

```
Apr  2 06:46:09 44a4c4605cff sshd[316]: error: buffer_get_bignum2_ret: negative numbers not supported
Apr  2 06:46:09 44a4c4605cff sshd[316]: fatal: buffer_get_bignum2: buffer error
```

**Comment by maxgoedjen** [comment]
No guarantee that this is what's triggering the failures with GitLab/Codeberg, but it makes sense with the nondeterministic aspect, in that some keys might overflow but others wouldn't. Trying to see if I misstate the length of any keys anywhere...

**Comment by maxgoedjen** [comment]
This is fixed in 1.0.1, available here https://github.com/maxgoedjen/secretive/releases/tag/v1.0.1

Thanks to everyone who helped! 🙏👍

**Comment by jrmguimberteau** [comment]
I am still having the same Issue as before with GitLab.

`jeremy@macbookpro ~ % ssh -Tv git@gitlab.com`
``` 
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to gitlab.com port 22.
debug1: Connection established.
debug1: identity file /Users/jeremy/.ssh/id_rsa type -1
debug1: identity file /Users/jeremy/.ssh/id_rsa-cert type -1
debug1: identity file /Users/jeremy/.ssh/id_dsa type -1
debug1: identity file /Users/jeremy/.ssh/id_dsa-cert type -1
debug1: identity file /Users/jeremy/.ssh/id_ecdsa type -1
debug1: identity file /Users/jeremy/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/jeremy/.ssh/id_ed25519 type -1
debug1: identity file /Users/jeremy/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/jeremy/.ssh/id_xmss type -1
debug1: identity file /Users/jeremy/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.8 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to gitlab.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ***
debug1: Host 'gitlab.com' is known and matches the ECDSA host key.
debug1: Found key in /Users/jeremy/.ssh/known_hosts:2
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: *** agent
debug1: Will attempt key: *** agent
debug1: Will attempt key: /Users/jeremy/.ssh/id_rsa
debug1: Will attempt key: /Users/jeremy/.ssh/id_dsa
debug1: Will attempt key: /Users/jeremy/.ssh/id_ecdsa
debug1: Will attempt key: /Users/jeremy/.ssh/id_ed25519
debug1: Will attempt key: /Users/jeremy/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: *** agent
debug1: Authentications that can continue: publickey
debug1: Offering public key: *** agent
debug1: Server accepts key: *** agent
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/jeremy/.ssh/id_rsa
debug1: Trying private key: /Users/jeremy/.ssh/id_dsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ecdsa
debug1: Trying private key: /Users/jeremy/.ssh/id_ed25519
debug1: Trying private key: /Users/jeremy/.ssh/id_xmss
debug1: No more authentication methods to try.
git@gitlab.com: Permission denied (publickey).
```

**Comment by blowery** [comment]
worked here! thanks!

**Comment by maxgoedjen** [comment]
@jrmguimberteau sometimes the agent doesn’t get restarted after installing a new update - in activity manager, try force quitting “SecretAgent” (it should immediately restart with a new PID)

**Comment by vordenken** [comment]
So I got to test it today and unfortunately its not 100 % working or maybe I'm doing something wrong.
It works on github & codeberg but not on my local machines. I even used new ubuntu vms to test it against and still no luck. 
This is the verbose log while trying to connect to my raspberry pi:
``` 
admin@Mac  ~  ssh -vT 192.168.1.3
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/admin/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to 192.168.1.3 [192.168.1.3] port 22.
debug1: Connection established.
debug1: identity file /Users/admin/.ssh/id_rsa type -1
debug1: identity file /Users/admin/.ssh/id_rsa-cert type -1
debug1: identity file /Users/admin/.ssh/id_dsa type -1
debug1: identity file /Users/admin/.ssh/id_dsa-cert type -1
debug1: identity file /Users/admin/.ssh/id_ecdsa type -1
debug1: identity file /Users/admin/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/admin/.ssh/id_ed25519 type -1
debug1: identity file /Users/admin/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/admin/.ssh/id_xmss type -1
debug1: identity file /Users/admin/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Raspbian-10+deb10u2
debug1: match: OpenSSH_7.9p1 Raspbian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.1.3:22 as 'admin'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 KEY
debug1: Host '192.168.1.3' is known and matches the ED25519 host key.
debug1: Found key in /Users/admin/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Will attempt key: /Users/admin/.ssh/id_rsa
debug1: Will attempt key: /Users/admin/.ssh/id_dsa
debug1: Will attempt key: /Users/admin/.ssh/id_ecdsa
debug1: Will attempt key: /Users/admin/.ssh/id_ed25519
debug1: Will attempt key: /Users/admin/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Authentications that can continue: publickey
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Authentications that can continue: publickey
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Authentications that can continue: publickey
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Authentications that can continue: publickey
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA KEY
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/admin/.ssh/id_rsa
debug1: Trying private key: /Users/admin/.ssh/id_dsa
debug1: Trying private key: /Users/admin/.ssh/id_ecdsa
debug1: Trying private key: /Users/admin/.ssh/id_ed25519
debug1: Trying private key: /Users/admin/.ssh/id_xmss
debug1: No more authentication methods to try.
admin@192.168.1.3: Permission denied (publickey).
```

One thing I can see from the logs, every ssh key is checked against the pi. Would it be possible to assign keys in secretive to hosts like in the ssh config file? (Or should I open a feature request for this?)

**Comment by maxgoedjen** [comment]
@vordenken from my reading of that log, I don't see any "public key accepted" step – are you sure your key is properly added to that device?

**Comment by maxgoedjen** [comment]
@jrmguimberteau the "you need to relaunch the agent" thing should be fixed by this: https://github.com/maxgoedjen/secretive/pull/86 😄

**Comment by jrmguimberteau** [comment]
😊

**Comment by OdysLam** [comment]
Hey,  I am encountering the same issue as I am trying to use it for AWS, but I need to set the private key a priori, otherwise it will fail for too many authentication failures. Apparently secretive checks against every key it has.  

I haven't found a way to tell secretive to use a specific key. Any idea?

**Comment by maxgoedjen** [comment]
@OdysLam I'm adding specific instructions around this scenario to the FAQ here: https://github.com/maxgoedjen/secretive/pull/176
(note: last I check, I think AWS requires RSA keys though? Which we don't currently support)
